package com.mycompany.usoarchivos.memoria;

import com.mycompany.usoarchivos.memoria.backend.About;
import com.mycompany.usoarchivos.memoria.excepciones.MostrarInfoExcepcion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author saien
 */
public class Pruebas extends JFrame {
    
     private About acercaDe = new About();
    /**
     * Creates new form Pruebas
     */
    public Pruebas() {

        initComponents();
        setJMenuBar(crearMenu());
        setVisible(true);
    }

    private JMenuBar crearMenu() {

        //Creamos la barra de opciones
        JMenuBar miBarra = new JMenuBar();

        //Creamos las opciones
        JMenu juego = new JMenu("Juego");
        JMenu reportes = new JMenu("Reportes");
        JMenu about = new JMenu("Acerca de");
        JMenu ayuda = new JMenu("Ayuda");
        JMenu nivel = new JMenu("Nivel");

        //Creamos los items para cada opcion
        JMenuItem nuevoJuego = new JMenuItem("Nuevo Juego");
        JMenuItem salir = new JMenuItem("Salir");
        JMenuItem estadisticas = new JMenuItem("Estadisticas");
        JMenuItem mejorJugador = new JMenuItem("Mejor Jugador");
        JMenuItem informacion = new JMenuItem("Sobre el juego");
        informacion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                try {
                    acercaDe.mostrarInformacion();
                } catch (MostrarInfoExcepcion e) {
                    JOptionPane.showMessageDialog(Pruebas.this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        JMenuItem instrucciones = new JMenuItem("Instrucciones");
        JMenuItem nivel1 = new JMenuItem("5 parejas");
        JMenuItem nivel2 = new JMenuItem("10 parejas");
        JMenuItem nivel3 = new JMenuItem("15 parejas");

        //para el nivel
        nivel.add(nivel1);
        nivel.add(nivel2);
        nivel.add(nivel3);

        //Para el Juego
        juego.add(nuevoJuego);
        juego.add(nivel);
        juego.add(salir);

        //Para Reportes
        reportes.add(estadisticas);
        reportes.add(mejorJugador);

        //para Acerda de
        about.add(informacion);

        //Para Ayuda
        ayuda.add(instrucciones);

        //agreagamos las opciones a la barra
        miBarra.add(juego);
        miBarra.add(reportes);
        miBarra.add(about);
        miBarra.add(ayuda);

        return miBarra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
